CREATE TABLE usermanager.users (
  ID INT NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(255) NOT NULL,
  USER_AGE INT NOT NULL,
  IS_ADMIN BIT(1) NOT NULL DEFAULT false,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID));

INSERT INTO usermanager.users (USER_NAME, USER_AGE) VALUES ('Sanya', '32');
INSERT INTO usermanager.users (USER_NAME, USER_AGE) VALUES ('Pasha', '25');
INSERT INTO usermanager.users (USER_NAME, USER_AGE) VALUES ('Kostya', '26');
INSERT INTO usermanager.users (USER_NAME, USER_AGE) VALUES ('Vova', '43');
